updated tekton pipelines for supermold
truefoundry/helm-charts pull request #11
Opened 2022-02-03 21:55 UTC by akashg3627

2022-02-18 09:45 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/pipeline-create-space.yaml
> +      default: develop.enthire.com
I think we should not have this defaults. They are going to change and be out of our control.

2022-02-18 09:47 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/pipeline-destroy-space.yaml
> +      default: https://truefoundry-server.develop.enthires.com
I think we should not have this defaults. They are going to change and be out of our control.

2022-02-18 09:47 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/pipeline-destroy-space.yaml
> +          value: '{"status": "5"}'
What is status: 5?

2022-02-18 09:48 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/pipeline-destroy-space.yaml
> +          value: '{"status": "6"}'
What is status 6?

2022-02-18 09:49 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/task-deploy-grafana-ingress.yaml
> +        kubectl rollout status deployment/grafana-$(params.namespace) -n "$(params.namespace)"
nice!

2022-02-18 09:51 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/task-send-api-request.yaml
> +   - name: send-api-request
why don't you just use curl instead of running python here?
Anyway, it works... I guess.

2022-02-18 09:52 UTC, lerrigatto commented on charts/truefoundry-pipelines/templates/task-space-error-handler.yaml
> +              value: '{"status": "6"}'
What is status 6?

2022-02-18 09:52 UTC, lerrigatto commented on charts/truefoundry-pipelines/values.yaml
> +  domain: develop.enthires.com
I don't think you need this twice. Just use the one and refer to that.

2022-02-18 18:28 UTC, akashg3627 commented on charts/truefoundry-pipelines/templates/pipeline-create-space.yaml
> +          value: '{"status": "2"}'
it's defined in tf-server, each value is associated with status of pipeline

2022-02-21 06:40 UTC, innoavator requested changes

2022-02-21 06:40 UTC, innoavator commented on charts/truefoundry-pipelines/templates/pipeline-create-space.yaml
> +          value: '{"status": "2"}'
Change these to strings

2022-02-21 06:45 UTC, shubham-rai-tf commented on charts/truefoundry-pipelines/templates/task-deploy-grafana.yaml
> +            grafana-$(params.namespace) grafana
This is a public chart. We should use a specific version of the chart

2022-02-21 12:51 UTC, innoavator approved these changes

2022-02-22 15:27 UTC, lerrigatto requested changes
Very few things left and we're good. Nice work.

2022-02-22 17:45 UTC, innoavator commented on charts/truefoundry-pipelines/values.yaml
> +  defaultServerUrl: https://truefoundry-server.develop.enthires.com
These shouldn't be hardcoded here - we should pass it from values in supermold

2022-02-22 17:45 UTC, innoavator commented on charts/truefoundry-pipelines/templates/configmap-dashboard-logs.yaml
> +  name: grafana-test-dashboard-logs
We should change this name?

2022-02-22 17:46 UTC, akashg3627 commented on charts/truefoundry-pipelines/templates/configmap-dashboard-logs.yaml
> +  name: grafana-test-dashboard-logs
change this to?

2022-02-22 17:47 UTC, akashg3627 commented on charts/truefoundry-pipelines/values.yaml
> +  defaultServerUrl: https://truefoundry-server.develop.enthires.com
you can always overwrite the values using supermold

2022-02-23 04:24 UTC, innoavator approved these changes

2022-02-23 04:24 UTC, merged